/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlankLayout: typeof import('./src/layouts/BlankLayout.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    CharacterCard: typeof import('./src/components/CharacterCard.vue')['default']
    CharacterList: typeof import('./src/components/CharacterList.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    GenderFilter: typeof import('./src/components/GenderFilter.vue')['default']
    ILocalCrystal: typeof import('~icons/local/crystal')['default']
    ILocalHeart: typeof import('~icons/local/heart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TariffCard: typeof import('./src/components/TariffCard.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
