# Generated by Django 5.2.6 on 2025-09-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.TextField(default='Привет! Я бот для общения с ИИ-персонажами.', help_text='Этот текст пользователь видит при первом запуске бота. Используется HTML.', verbose_name='Приветственное сообщение (/start)')),
            ],
            options={
                'verbose_name': 'Тексты бота',
                'verbose_name_plural': 'Тексты бота',
            },
        ),
        migrations.CreateModel(
            name='GroupUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://t.me/YourChannel', help_text='Ссылка на Telegram-канал или группу.', verbose_name='URL группы/канала')),
            ],
            options={
                'verbose_name': 'URL группы/канала',
                'verbose_name_plural': 'URL группы/канала',
            },
        ),
        migrations.CreateModel(
            name='WebAppUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://example.com', help_text='Основная ссылка на Telegram Web App.', verbose_name='URL для Web App')),
            ],
            options={
                'verbose_name': 'URL для Web App',
                'verbose_name_plural': 'URL для Web App',
            },
        ),
    ]
