# Generated by Django 5.2.6 on 2025-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottexts',
            name='start_message',
            field=models.TextField(default='Открыть приложение VPN', help_text='Этот текст пользователь видит при первом запуске бота. Используется HTML.', verbose_name='Приветственное сообщение (/start)'),
        ),
    ]
