# Generated by Django 5.2.6 on 2025-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_bottexts_start_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_time', models.IntegerField(default=5, verbose_name='Количество дней пробного периода')),
                ('trafic_day_limit', models.IntegerField(default=15, verbose_name='Лимит трафика в гигабайтах за день')),
            ],
            options={
                'verbose_name': 'Настройки VPN',
                'verbose_name_plural': 'Настройки VPN',
            },
        ),
    ]
