# Generated by Django 5.2.6 on 2025-10-14 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_vpnsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('datetime', models.DateTimeField(verbose_name='Дата/Время')),
                ('is_ok', models.BooleanField(verbose_name='Статус отправки')),
                ('rules', models.CharField(choices=[('OnlyPay', 'Только оплатившим'), ('NotPay', 'Только не оплатившим'), ('All', 'Всем')], default='All')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], verbose_name='Тип вложения')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('file_id', models.TextField(null=True)),
                ('mailing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='content.mailing')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
