# Generated by Django 5.2.6 on 2025-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('canceled', 'Отменен'), ('successful', 'Успешный')], default='pending', verbose_name='Статус платежа'),
        ),
    ]
