# Generated by Django 5.2.6 on 2025-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервера (для админки)')),
                ('api_url', models.URLField(help_text='Пример: http://your_server_ip:2053', verbose_name='URL API 3x-ui')),
                ('api_username', models.CharField(max_length=100, verbose_name='Логин API')),
                ('api_password', models.CharField(max_length=100, verbose_name='Пароль API')),
                ('inbound_id', models.PositiveIntegerField(default=1, verbose_name='ID входящего подключения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Сервер активен')),
            ],
            options={
                'verbose_name': 'VPN Сервер',
                'verbose_name_plural': 'VPN Серверы',
            },
        ),
    ]
