# Generated by Django 5.2.6 on 2025-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnserver',
            name='api_token',
            field=models.CharField(blank=True, null=True, verbose_name='Токен API'),
        ),
    ]
