# Generated by Django 5.2.6 on 2025-10-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_vpnserver_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnserver',
            name='domen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Домен и порт'),
        ),
        migrations.AddField(
            model_name='vpnserver',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Публичный ключ'),
        ),
        migrations.AddField(
            model_name='vpnserver',
            name='short_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий ID'),
        ),
        migrations.AddField(
            model_name='vpnserver',
            name='website_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя вебсайта'),
        ),
    ]
