# Generated by Django 5.2.6 on 2025-10-04 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.user', verbose_name='Кто пригласил')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('vless_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trial_activated', models.BooleanField(default=False, verbose_name='Триал активирован')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего пополнено')),
                ('is_vpn_client_active', models.BooleanField(default=False, verbose_name='Клиент VPN активен в 3x-ui')),
                ('total_bytes_limit', models.BigIntegerField(default=268435456000, verbose_name='Лимит трафика (байты)')),
                ('used_bytes', models.BigIntegerField(default=0, verbose_name='Использовано трафика (байты)')),
                ('last_traffic_update', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление трафика')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
