# Generated by Django 5.2.6 on 2025-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refferal_balance',
            field=models.IntegerField(default=0, verbose_name='Реферальный баланс'),
        ),
    ]
