# Generated by Django 5.2.6 on 2025-10-14 02:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_refferal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='vless_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID клиента в 3x-ui'),
        ),
    ]
