# Generated by Django 5.2.6 on 2025-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_vless_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='user',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего пополнено'),
        ),
    ]
