# Generated by Django 5.2.6 on 2025-10-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscription_total_paid_user_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notification_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведмление'),
        ),
    ]
